document.writeln("<div id=\"shoucangjia_box\"><div class=\"massage\">");
document.writeln("<div class=\"shoucang_header\"><div style=\"display:inline; width:150px; position:absolute\">&nbsp;把此酒店加入收藏<\/div>");
document.writeln("<span onClick=\"shoucangjia_box.style.visibility=\'hidden\'; mask.style.visibility=\'hidden\'\" style=\"float:right; font-size:14px;display:inline; cursor:hand\">× &nbsp;<\/span><\/div>");
document.writeln("");
document.writeln("<div style=\"margin:20px 10px 20px 10px;\">");
document.writeln("<a name=\"shoucang\">收藏到：<\/a> <a href=javascript:window.external.AddFavorite(location.href,document.title)><IMG  src=\/image\/icon\/ie.gif align=absMiddle border=0 alt=\"收藏到本电脑\"><\/a> <a href=javascript:window.open(\'http:\/\/shuqian.qq.com\/post?from=3&title=\'+encodeURIComponent(document.title)+\'&uri=\'+encodeURIComponent(document.location.href)+\'&jumpback=2&noui=1\',\'favit\',\'\');void(0)  ><IMG alt=收藏到QQ书签 src=\/image\/icon\/qq.gif align=absMiddle border=0><\/a> <A title=百度收藏 href=\"javascript:u=location.href;t=document.title;c = %22%22 + (window.getSelection ? window.getSelection() : document.getSelection ? document.getSelection() : document.selection.createRange().text);var url=%22http:\/\/cang.baidu.com\/do\/add?it=%22+encodeURIComponent(t)+%22&iu=%22+encodeURIComponent(u)+%22&dc=%22+encodeURIComponent(c)+%22&fr=ien#nw=1%22;window.open(url,%22_blank%22,%22scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes%22); void 0\"  ><IMG src=\/image\/icon\/baidu.gif alt=百度收藏 width=\"16\" height=\"16\" border=0><\/A>");
document.writeln("");
document.writeln("");
document.writeln(" <a href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void (vivi=window.open(\'http:\/\/vivi.sina.com.cn\/collect\/icollect.php?pid=http:\/\/www.jobui.com&title=\'+escape(d.title)+\'&url=\'+escape(d.location.href)");
document.writeln("+\'&desc=\'+escape(t),\'vivi\',\'scrollbars=no,width=480,height=480,left=75,top=20,status=no,resizable=yes\'));vivi.focus();\" title=\"收藏到新浪");
document.writeln("");
document.writeln("ViVi\"><img src=\'\/image\/icon\/vivi.gif\' alt=\'新浪ViVi\' border=\'0\'><\/a>  <a href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void(keyit=window.open(\'http:\/\/www.365key.com\/storeit.aspx?t=\'+escape(d.title)+\'&u=\'+escape(d.location.href)+\'&c=\'+escape(t),\'keyit\',\'scrollbars=no,width=475,height=575,left=75,top=20,status=no,resizable=yes\'));keyit.focus();\"  ><img src=\'\/image\/icon\/365key.gif\' alt=\'365Key网摘\' border=\'0\'><\/a> <a href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void");
document.writeln("");
document.writeln("(yesky=window.open(\'http:\/\/hot.yesky.com\/dp.aspx?t=\'+escape(d.title)+\'&u=\'+escape(d.location.href)+\'&c=\'+escape(t)");
document.writeln("");
document.writeln("+\'&st=2\',\'yesky\',\'scrollbars=no,width=400,height=480,left=75,top=20,status=no,resizable=yes\'));yesky.focus();\" title=\"天极网摘\"  ><img src=\'\/image\/icon\/yesky.gif\' alt=\'天极网摘\' border=\'0\'><\/a> <a href=\"javascript:d=document;t=d.selection?(d.selection.type!=\'None\'?d.selection.createRange().text:\'\'):(d.getSelection?d.getSelection():\'\');void(wozhai=window.open(\'http:\/\/www.wozhai.com\/wozhai\/Cento.asp#t=\'+escape(d.title)+\'&u=\'+escape(d.location.href)+\'&c=\'+escape(t),\'wozhai\',\'scrollbars=no,width=475,height=575,left=75,top=20,status=no,resizable=yes\'));wozhai.focus();\"  ><img src=\'\/image\/icon\/wozhai.gif\' alt=\'我摘\' border=\'0\'><\/a> <a href=\"javascript:t=document.title;u=location.href;e=document.selection?(document.selection.type!=\'None\'?document.selection.createRange().text:\'\'):(document.getSelection?document.getSelection():\'\');void(open(\'http:\/\/bookmark.hexun.com\/post.aspx?title=\'+escape(t)+\'&url=\'+escape(u)+\'&excerpt=\'+escape(e),\'HexunBookmark\',\'scrollbars=no,width=600,height=450,left=80,top=80,status=no,resizable=yes\'));\"  ><img src=\'\/image\/icon\/hexun.gif\' alt=\'和讯网摘\' border=\'0\'><\/a> <a href=\"#\" onClick=\"window.open(\'http:\/\/myweb.cn.yahoo.com\/popadd.html?url=\'+encodeURIComponent(document.location.href)+\'&title=\'+encodeURIComponent(document.title), \'Yahoo\',\'scrollbars=yes,width=780,height=550,left=80,top=80,status=yes,resizable=yes\');\"  ><IMG src=\"\/image\/icon\/yahoo.gif\"border=0><\/A>  <a href=\"javascript:q=(document.location.href);void(open(\"http:\/\/www.waakee.com\/submit.php?url=\"+encodeURIComponent(q),\"\",\"\"));\"  ><img src=\"\/image\/icon\/waakee18.gif\" width=\"18\" alt=\"收藏到挖客\" border=\"0\"><\/a> <a href=\"javascript:location.href=\'http:\/\/www.google.com\/bookmarks\/mark?op=add&bkmk=\'+encodeURIComponent(location.href)+\'&title=\'+encodeURIComponent(document.title)\"  ><img src=\/image\/icon\/google.gif alt=\"收藏到google\" border=0\/><\/a>");
document.writeln("<\/div>");
document.writeln("<\/div><\/div>");
document.writeln("<div id=\"mask\"><\/div>")