document.writeln("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">");
document.writeln("<div id=\"head\">");
document.writeln("<div id=\"top\">");
document.writeln("  <div class=\"logo\"> <a href=\"http://www.51booking.cn\"><img src=\"/image/logo_01.jpg\" alt=\"酒店预订 机票预订 旅游指南 - 中国商务订房网\" width=\"210\" height=\"78\" border=\"0\" /></a></div>");
document.writeln("  <div class=\"banner\">");
document.writeln("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http:\/\/download.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=7,0,19,0\" width=\"468\" height=\"60\">");
document.writeln("          <param name=\"movie\" value=\"\/swf\/2010351048460.swf\" \/>");
document.writeln("          <param name=\"quality\" value=\"high\" \/>");
document.writeln("          <embed src=\"\/swf\/hotel_index.swf\" quality=\"high\" pluginspage=\"http:\/\/www.macromedia.com\/go\/getflashplayer\" type=\"application\/x-shockwave-flash\" width=\"468\" height=\"60\"><\/embed>");
document.writeln("        <\/object>");
document.writeln("  </div>");
document.writeln("  <div class=\"login\">");
document.writeln("    <ul>");
document.writeln("	    <li><a href=\"http://www.51booking.cn/login/index.asp\" title=\"会员登录\">登 录</a> <span class=\"color_blue\">┆</span> <a href=\"http://www.51booking.cn/reg/?tar_class=comment\" title=\"免费注册\">注 册</a> </li>");
document.writeln("	    <li><a href=\"#\" onClick=\"this.style.behavior=\'url(#default#homepage)\';this.setHomePage(\'http://www.51booking.cn/\')\"><span>设为首页</span></a><span class=\"color_blue\">┆</span><a onMouseOver=\"window.external.addFavorite(\'http://www.51booking.cn\',\'中国商务订房网\')\" target=\"_self\" href=\"http://www.51booking.cn\"><span>加入收藏</span></a></li>");
document.writeln("    </ul>");
document.writeln("  </div>");
document.writeln("  <div class=\"clear\"></div>");
document.writeln("</div>");
document.writeln("<div id=\"menu\" style=\" background:url(/image/menu_02.png)\">");
document.writeln("  <ul>");
document.writeln("    <li class=\"menu_a2\"><a href=\"http://www.51booking.cn/\" title=\"首页\">首 页</a></li>");
document.writeln("	<li class=\"menu_a1\"><a href=\"http://www.51booking.cn/hotel/\" title=\"酒店预订\" class=\"Current\">酒店预订</a></li>");
document.writeln("	<li class=\"menu_a2\"><a href=\"http://www.51booking.cn/hotelchain/\" title=\"连锁酒店\"> 连锁酒店</a></li>");
document.writeln("	<li class=\"menu_a2\"><a href=\"http://www.51booking.cn/comment/\"title=\"酒店点评\">酒店点评</a></li>");
document.writeln("	<li class=\"menu_a2\"><a href=\"http://www.51booking.cn/plane/\" title=\"机票预订\">机票预订</a></li>");
document.writeln("	<li class=\"menu_a2\"><a href=\"http://www.51booking.cn/expo/\" title=\"会展信息\">会展信息</a></li>	");
document.writeln("	<li class=\"menu_a2\"><a href=\"http://www.51booking.cn/Destinations/\" title=\"目的地指南\">目的地指南</a></li>");

document.writeln("  </ul>");
document.writeln("</div>");
document.writeln("<div id=\"nav\">");
document.writeln("  <div id=\"navbox\"><ul><li class=\"nav_phone\"><img src=\"/image/phone.gif\" alt=\"预订电话\" style=\"width:16px; height:16px; margin-bottom:-4px;\" /> <span class=\"color_blue\">免费预订热线：400-646-8888</span></li>");
document.writeln("  <li><img src=\"/image/icon3.gif\" width=\"8\" height=\"9\" class=\"top_img\"/><a href=\"http://www.51booking.cn/login/order_login.asp\" title=\"订单管理\">订单管理</a></li>");
document.writeln("  <li><img src=\"/image/icon3.gif\" width=\"8\" height=\"9\" class=\"top_img\"/><a href=\"http://www.51booking.cn/member/\" title=\"个人信息\">个人信息</a>　</li>");
document.writeln("  <li><img src=\"/image/icon3.gif\" width=\"8\" height=\"9\" class=\"top_img\"/><a href=\"http://www.51booking.cn/member/jiangping.asp\" title=\"积分奖励\">积分奖励</a></li>");
document.writeln("  <li><img src=\"/image/icon3.gif\" width=\"8\" height=\"9\" class=\"top_img\"/><a href=\"http://www.51booking.cn/member/kefu.asp?title=联系我们\" title=\"客户服务\">客户服务</a></li>");
document.writeln("  <div class=\"clear\"></div>");
document.writeln("  </ul>");
document.writeln("  </div>");
document.writeln("</div>");
document.writeln("</div>");