document.writeln(" <DIV class=left_title>");
document.writeln("      <H4 class=h4>酒店点评排行<\/H4><\/DIV>");
document.writeln("      <DIV class=left_list>");
document.writeln("      <UL>");
document.writeln("	  ");
document.writeln('<LI>[<A title=青岛酒店评论 href=\/comment\/index_839.html >青岛<\/A>]&nbsp;<A title=青岛海景花园大酒店评论 href=\/hotel\/comment\/Qingdao\/2571.html>青岛海景花园大酒店<\/A><\/LI>');document.writeln('<LI>[<A title=香港酒店评论 href=\/comment\/index_871.html >香港<\/A>]&nbsp;<A title=香港迪士尼乐园酒店（Disneyland Hotel）评论 href=\/hotel\/comment\/Hongkong\/4165.html>香港迪士尼乐园酒店（<\/A><\/LI>');document.writeln('<LI>[<A title=三亚酒店评论 href=\/comment\/index_772.html >三亚<\/A>]&nbsp;<A title=金茂三亚丽思卡尔顿酒店评论 href=\/hotel\/comment\/Sanya\/6552.html>金茂三亚丽思卡尔顿酒<\/A><\/LI>');document.writeln('<LI>[<A title=丽江酒店评论 href=\/comment\/index_861.html >丽江<\/A>]&nbsp;<A title=丽江悦榕庄评论 href=\/hotel\/comment\/Lijiang\/4882.html>丽江悦榕庄<\/A><\/LI>');document.writeln('<LI>[<A title=澳门酒店评论 href=\/comment\/index_872.html >澳门<\/A>]&nbsp;<A title=澳门威尼斯人-度假村-酒店(The Venetian Macao- Resort- Hotel)评论 href=\/hotel\/comment\/Macau\/6013.html>澳门威尼斯人-度假村<\/A><\/LI>');document.writeln('<LI>[<A title=宁波酒店评论 href=\/comment\/index_866.html >宁波<\/A>]&nbsp;<A title=宁波华侨豪生大酒店评论 href=\/hotel\/comment\/Ningbo\/3095.html>宁波华侨豪生大酒店<\/A><\/LI>');document.writeln('<LI>[<A title=千岛湖酒店评论 href=\/comment\/index_1051.html >千岛湖<\/A>]&nbsp;<A title=千岛湖开元度假村评论 href=\/hotel\/comment\/Qiandaohu\/5116.html>千岛湖开元度假村<\/A><\/LI>');document.writeln('<LI>[<A title=香港酒店评论 href=\/comment\/index_871.html >香港<\/A>]&nbsp;<A title=香港迪士尼好莱坞酒店(Disney Hollywood Hotel)评论 href=\/hotel\/comment\/Hongkong\/4172.html>香港迪士尼好莱坞酒店<\/A><\/LI>');document.writeln('<LI>[<A title=广州酒店评论 href=\/comment\/index_744.html >广州<\/A>]&nbsp;<A title=广州海航威斯汀酒店（原广州天誉威斯汀酒店）评论 href=\/hotel\/comment\/Guangzhou\/3955.html>广州海航威斯汀酒店（<\/A><\/LI>');document.writeln('<LI>[<A title=威海酒店评论 href=\/comment\/index_955.html >威海<\/A>]&nbsp;<A title=威海蓝天宾馆评论 href=\/hotel\/comment\/Weihai\/2726.html>威海蓝天宾馆<\/A><\/LI>');
document.writeln("		<\/UL>");
document.writeln("		<\/DIV>");
document.writeln("	<\/DIV>")
